project:
  type: website
  output-dir: docs
  render:
    - about.qmd
    - index.qmd
    - achievements.qmd
    - events.qmd
    - ha.qmd
    - history.qmd
    - news.qmd
    - organization.qmd
    - publications.qmd
    - resources.qmd
    - scope.qmd
    - status.qmd
    - taskforces.qmd
    - communication/

website:
  title: "Oncology Estimand WG"
  navbar:
    background: success
    left:
    - text: "About"
      menu:
        - text: "About"
          href: index.html
        - text: "History"
          href: history.html
        - text: "Scope"
          href: scope.html
        - text: "Status"
          href: status.html
        - text: "Organization"
          href: organization.html
        - text: "Achievements per year"
          href: achievements.html
    - text: "Task forces"
      href: taskforces.html
    - text: "Health authority interactions"
      href: ha.html
    - text: "Publications"
      href: publications.html
    - text: "Events"
      href: events.html
    - text: "Newsletters"
      href: news.html
    - text: "Further resources"
      href: resources.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

