project:
  type: website
  output-dir: docs
  render:
    - about.qmd
    - updates.qmd
    - index.qmd
    - achievements.qmd
    - events_upcoming.qmd
    - events_past.qmd
    - ha.qmd
    - history.qmd
    - news.qmd
    - organization.qmd
    - publications.qmd
    - resources.qmd
    - scope.qmd
    - status.qmd
    - taskforces.qmd
    - communication/
    - code.qmd
    - collaborations.qmd
    - nalt_9862938.qmd
    - videos.qmd

website:
  title: "Oncology Estimand WG"
  navbar:
    background: success
    left:
    - text: "About"
      menu:
        - text: "About"
          href: index.html
        - text: "Updates of this page"
          href: updates.html
        - text: "History"
          href: history.html
        - text: "Scope"
          href: scope.html
        - text: "Status"
          href: status.html
        - text: "Organization"
          href: organization.html
        - text: "Collaborations"
          href: collaborations.html
        - text: "Achievements per year"
          href: achievements.html
    - text: "Task forces"
      href: taskforces.html
    - text: "Health authority interactions"
      href: ha.html
    - text: "Publications"
      href: publications.html
    - text: "Code"
      href: code.html
    - text: "Events"
      menu:
        - text: "Upcoming events"
          href: events_upcoming.html
        - text: "Past events"
          href: events_past.html
    - text: "Communication"
      menu:
        - text: "Newsletters"
          href: news.html
        - text: "Linkedin videos"
          href: videos.html
    - text: "Further resources"
      href: resources.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

