---
title: "Oncology estimand working group: achievements per year"
date: "Last change: `r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
bibliography: biblio.bib
---

```{r setup, include = FALSE, echo = FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)
```

# Achievements 2019

The WG created a platform for sharing experience and ensuring common understanding of estimands in oncology trials across industry and continues to grow both in terms of members and companies. The discussions within the WG advanced in all subteams and several manuscripts are under preparation. As planned, the initial content was disseminated in 2019 via several statistical conferences in Europe and US. One publication was submitted in 2019 and several submissions are planned in 2020. The WG engaged with the Clinical community and submitted abstracts to several Clinical conferences in collaboration with key opinion leaders and industry clinicians, a poster was presented at ESMO. Similarly, the collaboration with Health Authorities is ongoing and expected to continue over several years. Furthermore, the SWG also had some initial discussions with academia statisticians on potential topics for collaboration in future.

The WG highlighted various estimand problems in Oncology and shared the view of the SWG in many presentations at conferences in Europe and US and in collaboration with EMA and FDA:

* invited talk at HTA EFSPI SIG 1-day event (Berlin, February 2019)
* session (4 talks) at DAGStat (Munich, March 2019)
* session (3 talks by WG members and EMA discussant) at LiDS conference (Pittsburgh, June 2019)
* 2 talks at PSI conference (London, June 2019)
* 1 talk at DIA Annual meeting (San Diego, June 2019)
* 1 talk at ISCB conference (Leuven, July 2019)
* session (4 talks and FDA discussant) at JSM (Denver, July 2019)
* talk at EFSPI regulatory (Basel, September 2019)
* session (3 talks) and invited to participate in a panel discussion at ASA Biopharmaceutical Section Regulatory-Industry Statistics Workshop (September 2019)
* talk at ISOQoL conference (San Diego, October 2019)
* Poster on estimands in adjuvant renal cell carcinoma in collaboration with key opinion leaders and industry clinicians at ESMO  (September 2019)

# Achievements 2020

Despite the many challenges in 2020 the SIG was able to relevantly contribute to the implementation of the estimand addendum in drug development in oncology and beyond. Key achievements are:

* The intercontinental team spirit that allowed to come up with a rapid response to COVID-19 pandemic: a [slidedeck](https://oncoestimand.github.io/oncowg_webpage/data/onco_estimand_COVID-19_slidedeck_v1.pdf) discussing the impact of the pandemic on a trial's estimand was published on the webpage less than five weeks after WHO declared the pandemic. A [paper](https://doi.org/10.1080/19466315.2020.1785543) followed only a few weeks later.
* Several [publications](https://oncoestimand.github.io/oncowg_webpage/oncoestimand.html#publications) of the SIG were published this year, and several more are in their last rounds of revision.
* The SIG organized two webinars that brought together drug developers, academics, and regulators to discuss topics around estimands in oncology and beyond:
  + [Estimands addendum is final: Anything new for oncology?](http://bbs.ceb-institute.org/?p=1453): The highlight here was that several clinical colleagues contributed as presenters and panelists.
  + [RCTs meeting causal inference: principal stratum strategy and beyond.](http://bbs.ceb-institute.org/?p=1587)
* The SIG organized sessions and was invited to speak at virtual US conferences (JSM, ASA-FDA workshop, Deming conference on applied statistics). Further [talks](https://oncoestimand.github.io/oncowg_webpage/conferences.html#webinar_of_the_basel_biometrics_section:_impact_of_covid-19_on_clinical_trials) were given at several occasions.
* The SIG organized TCs with seven Health Authorities (FDA, HC, Swissmedic, China, Japan, Taiwan, MHRA) to share its work and get input on future directions.
* Set up a webpage ([www.oncoestimand.org](http://www.oncoestimand.org/)) to foster sharing of information and generated content such as presentations and publications. As of today, the SIG has 54 members (20 from Europe, 29 from US, and 5 from Asia) representing 28 companies.
Currently the SIG is regrouping in task forces dedicated to eight topics that are considered relevant to develop implementation of the addendum further in oncology clinical trials. So expect more output in 2021!

# Achievements 2021

The group has evolved into a global network of statisticians in industry and regulatory agencies that continues to contribute to the implementation of the ICH E9 addendum. Key achievements are:

* Several [publications](publications.html) of the SIG appeared this year.
* Together with the EFPIA estimands implementation working group the SIG organized two webinars targeted at a broad audience of Clinicians, Investigators, Regulatory Experts, Medical Writers, Ethics Committees, Statisticians:
  + PSI EIWG Webinar: Estimands in Oncology - How and Why. [Webinar 1 EU](https://oncoestimand.github.io/oncowg_webpage/docs/events.html#01062021:_PSI_EIWG_Webinar:_Estimands_in_Oncology_-_How_and_Why) | [Webinar 2 US](https://oncoestimand.github.io/oncowg_webpage/docs/events.html#28092021:_DIA_webinar:_Estimands_How_and_Why_-_A_Real_Life_Case_Study_in_Oncology).
* The SIG organized sessions and was invited to speak at conferences (Duke Industry Statistics Symposium, Society for clinicial trials, JSM, ASA-FDA workshop, Deming conference on applied statistics). Further [talks](https://oncoestimand.github.io/oncowg_webpage/conferences.html#webinar_of_the_basel_biometrics_section:_impact_of_covid-19_on_clinical_trials) were given at several occasions.
* Members of the SIG were also invited to FDA OCE Project Significant TCs to talk about application of estimands to decentralized trials and comment on non-proportional hazards.
* As a higlight of 2021 nine task forces were kicked off who have started their work. Find them all, including rosters and objectives, [here](taskforces.html).
* As of November 2021, the SIG has has 77 members (30 from Europe, 38 from US, and 9 from Asia) representing 36 companies / institutions, see [status](status.html).
* As an outlook in 2022 we plan to organize webinars reporting on the content that the task forces have generated so far. We also plan to get involved with our Health Authority partners again.




