---
title: "Oncology estimand working group: achievements per year"
date: last-modified
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
bibliography: biblio.bib
---

```{r setup, include = FALSE, echo = FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)
panderOptions('table.alignment.default', function(df){ifelse(sapply(df, is.numeric), 'right', 'left')})

path <- getwd()

## =================================================================
## functions
## =================================================================
source(file = paste(path, "/tools/mydisp.r", sep = ""))

## =================================================================
## member list
## =================================================================
email <- as.data.frame(read_excel(paste(path, "/data/members.xlsx", sep = ""), col_types = NULL))

## function to display
ind <- email[, "Type"] == "Industry" 
loc <- email[ind, "Location"]
com <- email[ind, "Institution"]
```

# Achievements 2023

The group continues to be an influential player in the global discussion on estimands between industry, regulators, and academia. Key achievements in 2023 are:

- General activities listed as achievements in last years below are continued by the group.
- Seven [publications](publications.html) of the SIG appeared or have been submitted this year (numbers 9-15 in [publication list](publications.html)). In total, (at least) 15 published papers and numerous talks meanwhile come out of this group.
- The SIG gave many talks and organized sessions at conferences and webinars, see [events](events_past.html). Some highlights:
  - Jonathan gave an invited talk at the [Duke industry statistics symposium 2023](https://oncoestimand.github.io/oncowg_webpage/docs/events_past.html#duke-industry-statistics-symposium-2023).
  - Co-organized and contributed to a BBS seminar on [Quantification of risk: ask the right questions or time to apply the estimand framework to safety!](https://baselbiometrics.github.io/home/docs/events_past.html#quantification-of-risk-ask-the-right-questions-or-time-to-apply-the-estimand-framework-to-safety)
  - Organized two sessions at the [LIDS 2023 conference](https://oncoestimand.github.io/oncowg_webpage/docs/events_past.html#lifetime-data-science-conference-lids) in Raleigh.
  - An entire session organized by the SIG at the [PSI 2023 conference](https://oncoestimand.github.io/oncowg_webpage/docs/events_past.html#psi-conference) in London. Hong Tian, Konstantina Skaltsa, Stefan Englert, Lynda Grinsted, Elizabeth Pilling, and Yufei Wang presented outcomes from various taskforces to a completely full room.
  - Invited talk and pre-conference course on "Causal Inference in Randomized Controlled Trials" at [JSM in Toronto](events_past.html#joint-statistical-meetings).
  - Panel discussion at [ASA Biopharmaceutical Section Regulatory Industry Statistics Workshop](events_past.html#asa-biopharmaceutical-section-regulatory-industry-statistics-workshop).
  - Stefan and Francois contributed talks to a [BBS seminar](events_past.html#seminar-of-the-basel-biometric-society-estimands-in-early-development-ed-across-therapeutic-areas) on _Estimands in Early Development (ED) across Therapeutic Areas_.
  - Kaspar was invited to present in an FDA / Lungevity TC within [Project significant](https://www.fda.gov/about-fda/oncology-center-excellence/project-significant-statistics-cancer-trials) on _Impact of Cross-over in the Evaluation of Overall Survival in cancer RCTs_, find slides [here](events_past.html#fda-lungevity-project-significant).
  - Evgeny was invited for a plenary talk at the [Nordic lymphoma meeting](http://www.nordic-lymphoma.org/plenary-meeting/). It is great to see the rising interest in estimands also in the clinical community! Find slides [here](events_past.html#nordic-lymphoma-group-plenary-meeting).
  - Stefan contributed a talk to the yearly [APF workshop](events_past.html#apf-workshop-early-phase-clinical-development-estimands-biomarkers-and-decision-making).
- As a spin-off of our WG, a few colleagues from the [PRO task force](taskforces.html#patient-reported-outcomes) submitted a proposal to [EFSPI](https://www.efspi.org/) for a [special interest group](https://efspi.org/EFSPI/SIGS/EFSPI/Special_Interest_Groups/SIGS.aspx). We except to start this very soon under the formal [EFSPI](https://www.efspi.org/) umbrella.
- As of December 2023, the SIG has `r length(loc)` members (`r sum(loc == "Europe", na.rm = TRUE)` from Europe, `r sum(loc == "NorAm", na.rm = TRUE)` from US, and `r sum(loc == "Asia", na.rm = TRUE)` from Asia) representing `r length(unique(com))` companies / institutions, see [status](status.html).

# Achievements 2022

The group continues to be an influential player in the global discussion on estimands between industry, regulators, and academia. Key achievements in 2022 are:

- General activities listed as achievements in last years below are continued by the group.
- Several [publications](publications.html) of the SIG appeared or have been submitted this year. 
- Two SIG papers published in 2021 were among the five most downloaded in Pharmaceutical statistics in 2021, see [publications](publications.html).
- The SIG gave many talks and organized sessions at conferences and webinars, see [events](events_past.html). Some highlights:
  - An entire session organized by the SIG at the [PSI conference](events_past.html#psi-annual-conference).
  - The SIG organized two sessions at the [ASA FDA workshop](https://ww2.amstat.org/meetings/biop/2022/) ("Adjusted and Unadjusted Estimate in Clinical Trials: Reward, Risk and Myth" and "Estimands in Oncology: A Topical Panel Discussion"), see [events page](events_past.html#asa-biopharmaceutical-section-regulatory-industry-statistics-workshop).
  - DIA held a webinar in China, with a talk by Jiajun Xu from the [conditional and marginal effect force](taskforces.html#conditional-vs.-marginal-effects). With a peak attendance of 4460 colleagues this likely sets a new record for a talk by this WG!
  - Together with ASA NJ chapter the WG co-organized a webinar [ASA New Jersey Chapter Webinar Series: Getting the question right: Applying the Estimand and Target Trial Frameworks with External Controls
](communication/20221202_ASA_NJ_TTF_estimands.pdf).
- On June 28th & 29th we had two full group TCs with regulators attending where we presented our work. Slidedecks are available [here](ha.html).
- [eunethta](https://www.eunethta.eu/) is currently seeking comments for their set of guidelines for a joint clinical assessment of European HTA bodies. Several of the WG's papers were cited in [EFPIA's response to deliverable 4.5](https://www.eunethta.eu/d4-5/).
- As of November 2022, the SIG has 97 members (36 from Europe, 50 from US, and 10 from Asia) representing 48 companies / institutions, see [status](status.html).

# Achievements 2021

The group has evolved into a global network of statisticians in industry and regulatory agencies that continues to contribute to the implementation of the ICH E9 addendum. Key achievements are:

-   Several [publications](publications.html) of the SIG appeared this year.
-   The SIG has built a network of individuals with expertise and credibility in the broader biostatistical and drug development community. Testament to that is the fact that SIG members are regularly invited to review and comment on scientific publications in the field.
-   Invited by the [EFSPI/EFPIA estimands implementation working group](https://www.efspi.org/EFSPI/Working_Groups/EFSPI_EFPIA_EIWG.aspx) the SIG organized two webinars targeted at a broad audience of Clinicians, Investigators, Regulatory Experts, Medical Writers, Ethics Committees, Statisticians:
    - [PSI EIWG Webinars](events_past.html#psi-eiwg-webinar-estimands-in-oncology---how-and-why) (2 events, one for EU and one for US): Estimands in Oncology - How and Why.
    - The WG also organized a [DIA Webinar](events_past.html#dia-webinar-estimands-how-and-why---a-real-life-case-study-in-oncology) with the same target audience, including FDA discussants.
-   Our SIG is also formally represented in the [EFSPI/EFPIA estimands implementation working group](https://www.efspi.org/EFSPI/Working_Groups/EFSPI_EFPIA_EIWG.aspx).
-   The SIG organized sessions and was invited to speak at conferences (Duke Industry Statistics Symposium, Society for clinicial trials, JSM, ASA-FDA workshop, ISOQoL). Further [talks](events_past.html) were given at several occasions.
-   Members of the SIG were also invited to FDA OCE Project Significant TCs to talk about application of estimands to decentralized trials and comment on non-proportional hazards.
-   As a higlight of 2021 nine task forces were kicked off who have started their work on new topics relevant to the implementation of the addendum, and applying the addendum to extended areas such as, e.g., real-worl data. Find them all, including rosters and objectives, [here](taskforces.html).
-   As of November 2021, the SIG has has 77 members (30 from Europe, 38 from US, and 9 from Asia) representing 36 companies / institutions, see [status](status.html).
-   As an outlook in 2022 we plan to organize webinars reporting on the content that the task forces have generated so far. One goal is also to broaden our outreach and present not only at statistical but also at clinical conferences. We also plan to get involved with our Health Authority partners again.

# Achievements 2020

Despite the many challenges in 2020 the SIG was able to relevantly contribute to the implementation of the estimand addendum in drug development in oncology and beyond. Key achievements are:

-   The intercontinental team spirit that allowed to come up with a rapid response to COVID-19 pandemic: a [slidedeck](talks/other/onco_estimand_COVID-19_slidedeck_v1.pdf) discussing the impact of the pandemic on a trial's estimand was published on the webpage less than five weeks after WHO declared the pandemic. A [paper](https://doi.org/10.1080/19466315.2020.1785543) followed only a few weeks later.
-   Several [publications](publications.html) of the SIG were published this year, and several more are in their last rounds of revision.
-   The SIG organized two webinars that brought together drug developers, academics, and regulators to discuss topics around estimands in oncology and beyond:
    -   [Estimands addendum is final: Anything new for oncology?](https://baselbiometrics.github.io/home/docs/events_past.html#29062020:_Joint_EFSPI__BBS_Webinar:_Estimands_addendum_is_final:_Anything_new_for_oncology): The highlight here was that several clinical colleagues contributed as presenters and panelists.
    -   [RCTs meeting causal inference: principal stratum strategy and beyond.](https://baselbiometrics.github.io/home/docs/events_past.html#07092020:_BBS_Webinar_RCTs_meeting_causal_inference:_principal_stratum_strategy_and_beyond)
-   The SIG organized sessions and was invited to speak at virtual US conferences (JSM, ASA-FDA workshop, Deming conference on applied statistics). Further [talks](events_past.html) were given at several occasions.
-   The SIG organized TCs with seven Health Authorities (FDA, HC, Swissmedic, China, Japan, Taiwan, MHRA) to share its work and get input on future directions.
-   Set up a webpage ([www.oncoestimand.org](http://www.oncoestimand.org/)) to foster sharing of information and generated content such as presentations and publications. As of today, the SIG has 54 members (20 from Europe, 29 from US, and 5 from Asia) representing 28 companies. Currently the SIG is regrouping in task forces dedicated to eight topics that are considered relevant to develop implementation of the addendum further in oncology clinical trials. So expect more output in 2021!

# Achievements 2019

The WG created a platform for sharing experience and ensuring common understanding of estimands in oncology trials across industry and continues to grow both in terms of members and companies. The discussions within the WG advanced in all subteams and several manuscripts are under preparation. As planned, the initial content was disseminated in 2019 via several statistical conferences in Europe and US. One publication was submitted in 2019 and several submissions are planned in 2020. The WG engaged with the Clinical community and submitted abstracts to several Clinical conferences in collaboration with key opinion leaders and industry clinicians, a poster was presented at ESMO. Similarly, the collaboration with Health Authorities is ongoing and expected to continue over several years. Furthermore, the SWG also had some initial discussions with academia statisticians on potential topics for collaboration in future.

The WG highlighted various estimand problems in Oncology and shared the view of the SWG in many presentations at conferences in Europe and US and in collaboration with EMA and FDA:

-   invited talk at HTA EFSPI SIG 1-day event (Berlin, February 2019)
-   session (4 talks) at DAGStat (Munich, March 2019)
-   session (3 talks by WG members and EMA discussant) at LiDS conference (Pittsburgh, June 2019)
-   2 talks at PSI conference (London, June 2019)
-   1 talk at DIA Annual meeting (San Diego, June 2019)
-   1 talk at ISCB conference (Leuven, July 2019)
-   session (4 talks and FDA discussant) at JSM (Denver, July 2019)
-   talk at EFSPI regulatory (Basel, September 2019)
-   session (3 talks) and invited to participate in a panel discussion at ASA Biopharmaceutical Section Regulatory-Industry Statistics Workshop (September 2019)
-   talk at ISOQoL conference (San Diego, October 2019)
-   Poster on estimands in adjuvant renal cell carcinoma in collaboration with key opinion leaders and industry clinicians at ESMO (September 2019)
