---
title: "Code accompanying papers"
date: last-modified
execute:   
  freeze: auto  # re-render only when source changes
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
bibliography: biblio.bib
---

# Publications

All papers co-written by the group are available [here](publications.html). There, links to the below code is available for respective papers.

# Code repositories

For the following publications code has been made available on github:

* Bornkamp, B., Rufibach, K., Lin, J., Liu, Y., Mehrotra, D., Roychoudhury, S., Schmidli, H., Shentu, Y., Wolbers, M. _Principal Stratum Strategy: Potential Role in Drug Development_ (2021). Pharmaceutical Statistics, **20**, 737-751. | [doi](https://doi.org/10.1002/pst.2104) | [arxiv](https://arxiv.org/abs/2008.05406) | [github](https://github.com/oncoestimand/princ_strat_drug_dev) | [markdown](https://oncoestimand.github.io/princ_strat_drug_dev/princ_strat_example.html) | **This paper was the 4th most downloaded paper that appeared in 2021 in [Pharmaceutical Statistics](https://onlinelibrary.wiley.com/journal/15391612).**
* Rufibach, K., Grinsted, L., Li, J., Weber, H.J., Zheng, C., and Zhou, J. _Quantification of Follow-up Time in Oncology Clinical Trials with a Time-to-Event Endpoint: Asking the Right Questions._ (2023). Pharmaceutical Statistics, **22**(4), 671-691. | [arXiv](https://doi.org/10.48550/arxiv.2206.05216) | [github](https://github.com/oncoestimand/quantFU) | [markdown](https://oncoestimand.github.io/quantFU/quantFU.html) |.
* Weber, H. J., Corson, S., Li, J., Mercier, F., Roychoudhury, S., Sailer, M. O., Sun, S., Todd, A., Yung, G. _Duration of and time to response in oncology clinical trials from the perspective of the estimand framework._ (2023+). Pharmaceutical Statistics, to appear. | [arXiv](https://arxiv.org/abs/2212.10911) | [doi](https://doi.org/10.1002/pst.2340) | [github](https://github.com/oncoestimand/dor) | [markdown](https://oncoestimand.github.io/dor/dor.html) |
