---
title: "Oncology estimand working group: conferences and presentations"
author: "A cross-industry international working group"
date: '`r Sys.setlocale("LC_TIME", "C"); format(Sys.Date(), "%d %b %Y")`'
output:
  html_document:
    keep_md: true
    toc: yes
    toc_depth: 2
    toc_float:
      collapsed: yes
      smooth_scroll: yes
      number_sections: true
  github_document: 
    toc: true
    toc_depth: 2
  pdf_document:
    toc: yes
  word_document:
    fig_caption: yes
    toc: yes
---

```{r setup, include = FALSE, echo = FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)

## talks
path <- getwd()
talks <- as.data.frame(read_excel(paste(path, "/data/conferences.xlsx", sep = ""), col_types = NULL))
talks <- (talks %>% filter(is.na(Speaker1) == FALSE))
```

[Back to main site](http://www.oncoestimand.org)

```{r echo = FALSE, message = FALSE, warning = FALSE, include = FALSE}

# how to do this with child documents: https://gist.github.com/rmoff/a043676a2f084b81a434

out1 <- NULL
for (i in 1:nrow(talks)){
  out1 <- c(out1, knit_expand('tools/conf1.Rmd'))
}

# the "knit" command somehow produces unwanted output, this is why I assign its output to a and use a separate chunk to display a
a <- knit(text = unlist(paste(out1, collapse = '\n')), quiet = TRUE)
```

```{r conferences, echo = FALSE, message = FALSE, warning = FALSE, results = "asis"}
cat(a)
```



