---
title: "Interactions with Health Authorities and the ICH E9(R1) working group"
date: "Last change: `r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
---

We are grateful for ongoing collaboration and regular dialogue to statisticians from European Medicines Agency (EMA), 
Medicines and Healthcare products Regulatory Agency (MHRA, UK), U.S. Food and Drug Administration (FDA), Pharmaceuticals and Medical Devices Agency (PMDA, Japan), Health Canada, Swissmedic, National Medical Products Administration (NMPA, China) and Center for Drug Evaluation (CDE, Taiwan). 

In September 2020, the WG presented to all these regulatory agencies the results of the work that had been done within the WG until then. The slidedeck with a concise summary of all the submitted papers is available for [download](data/202009 Summary of Onco Estimand WG papers.pdf).

We also thank Keaven Anderson (Merck) and Frank Bretz (Novartis) for their support.

