---
title: "New-anti lymphoma treatment (NALT) as intercurrent event for PFS in lymphoma"
author: 
- name: Kaspar Rufibach (input and review of Roche colleagues, especially Marcel Wolbers, gratefully acknowledged)
  affiliation: Methods, Collaboration, and Outreach (MCO) Group, Roche
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
bibliography: biblio.bib
---

# Context

New anti-lymphoma (NALT) therapy before progression (PD) for progression-free survival (PFS) in lymphoma trials can be considered an intercurrent event (ICE) in the framework of the [ICH E9 addendum](https://database.ich.org/sites/default/files/E9-R1_Step4_Guideline_2019_1203.pdf) addendum. This raises the following questions:

- What clinical question are we interested in?
- Which of the five estimand strategies in the [ICH E9 addendum](https://database.ich.org/sites/default/files/E9-R1_Step4_Guideline_2019_1203.pdf) help answering the clinical question of interest?
- How should we estimate the chosen estimand?

# Estimand 

## (implicit) Hypothetical strategy for the ICE of NALT

In the 00's, i.e. in the pre-estimand addendum era, there already was a debate whether one should censor at start of NALT in lymphoma indications, and this debates appears to go on until today. The FDA guidance [*Guidance for industry clinical trial endpoints for the approval of cancer drugs and biologics*](https://www.fda.gov/regulatory-information/search-fda-guidance-documents/clinical-trial-endpoints-approval-cancer-drugs-and-biologics) @fda_endpoints recommends to censor at date of "new anticancer treatment". This is in line with [Cheson et al. [-@cheson_07]](papers/Cheson%20et%20al%20(2007)%20Revised%20response%20criteria%20for%20malignant%20lymphoma.pdf) who writes 

> ...in studies in which failure to respond without progression is considered an indication for another therapy, such patients should be censored at that point for the progression analysis.

This estimator, i.e. censoring at start of NALT, (implicitly) corresponds to applying a **hypothetical** strategy for the ICE of NALT. **This means it specifies interest in a treatment effect in a world where NALT would not exist.**

## (implicit) Treatment policy strategy for the ICE of NALT

Interestingly, in another highly cited paper by [Fleming et al. [-@fleming_09]](papers/Fleming et al (2009) Issues in Using PFS When Evaluating Oncology Products.pdf), it is recommended that

> ...patients should not be censored at the time other treatments are initiated when analyzing the PFS end point...

This corresponds to a **treatment policy** estimand. This is also implicitly the recommendation in the EMA guidance [Appendix 1 to the guideline on the evaluation of anticancer medicinal products in man](https://www.ema.europa.eu/en/documents/scientific-guideline/appendix-1-guideline-evaluation-anticancer-medicinal-products-man-methodological-consideration-using_en.pdf):

> The time of the progression or recurrence event is determined using the first date when there is documented evidence that the
criteria have been met, even in situations where progression is observed after one or more missed visits, treatment discontinuation, or **new anti-cancer treatment**.

**A treatment policy strategy for the ICE of NALT can be interpreted as treatment effect for the treatment strategy**

_start with therapy at randomization + switch to approved NALT before PD according to investigator's choice._

**This appears to come closest to the treatment effect that will be observed in the "real world" once the drug is approved, because approved NALTs will be available.**

A treatment policy strategy for start of 2nd line therapy for an endpoint of PFS has, e.g., been implemented in all pivotal Roche Gazyva trials (Gadolin, Gallium, Goya).

# FDA view on hypothetical strategy in general

[Ionan et al [-@ionan_22]](papers/Ionan et al (2023), Clinical and Statistical Perspectives on the Estimand Framework Implementation.pdf) comment:

> For example, in the case of a hypothetical strategy, it is necessary to describe precisely the nature of the hypothetical scenario under which estimation of treatment effect is of interest and why the actual scenario in which the intercurrent event occurs is problematic for the interpretation of the treatment effect. It is important to justify the relevance of the corresponding treatment effect to be estimated, and the statistical model that accurately captures the specific chosen hypothetical scenario. 

and

> The clinical and regulatory interest of such hypotheticals is limited and would usually depend on a clear understanding of why and how the intercurrent event, or its consequences, would be expected to be different in clinical practice than in the clinical trial.

So, using a hypothetical strategy for the ICE of NALT corresponds to interest in a treatment effect in a world where **such NALT would not exist**.

Similarly, FDA colleagues [Mayo and Kim [-@mayo_23]](papers/Mayo and Kim (2023) What can be Achieved with the Estimand Framework.pdf) discourage use of hypothetical estimands:

> More precisely defining the clinical question and corresponding estimand has led to some challenges and differences in perspectives. For example, it is uncommon that we have found a hypothetical strategy to be the most relevant one for the primary clinical question used in regulatory decision-making (with exceptions, e.g., a pandemic leading to temporary site closures that are not expected to occur in general clinical practice in the future).

# Estimation methods

## Censoring 

Some of the estimand aspects have been mingled into the, what we now call "estimand discussion" in the past. Most specifically, the question about "censoring". Censoring is a statistical technique to estimate an estimand with a hypothetical strategy for an ICE. As such, "censoring" cannot be part of the _estimand_ definition, rather it pertains to the _estimation method_.

Furthermore, for an estimator based on censoring to give an unbiased estimate of the targeted estimand which uses a hypothetical strategy for the ICE of interest one needs to make quite strong assumptions, either that censoring is **random** or at least **independent**. The latter is a slightly weaker assumption, see [Andersen [-@andersen_05]](papers/Andersen (2005, encyclopedia) Censored data.pdf). Not that **informative censoring** is yet another concept -- although often used in pharmaceutical statistician's discussions (in the sense of "non-informative") it is actually mathematically not the correct term for what we are talking about here, see [Andersen [-@andersen_05]](papers/Andersen (2005, encyclopedia) Censored data.pdf).

## Other estimators of an estimand with a hypothetical strategy for an ICE

Sometimes it might be plausible that subjects who discontinued treatment early would have done worse than those who did not, **even in a hypothetical world where they had stayed on treatment**. One method for imputing T2E endpoints in this case is the method by Jackson et al. [-@jackson_14] which is implemented in the [InformativeCensoring](https://cran.r-project.org/package=InformativeCensoring) [R](https://cran.r-project.org) package. A caveat of this method is that it depends on $\gamma$, the hypothesized size of the step change in the log hazard at censoring. This makes it not easy to have this approach as a primary analysis, but potentially as sensitivity analysis.

Alternatively, inverse-probability of censoring weights (IPCW) has also been proposed. Here, patients who do not have the intercurrent event serve as proxies for those who do. For estimation we need covariates that make PFS and the intercurrent event conditionally independent. An advantage of IPCW is that you can include updated time-varying covariates in the _probability of censoring_ model, which might make the required assumptions more plausible. One practical issue with the approach are unstable weights. Again, this can most likely be positioned as sensitivity analysis.

## If you censor treatment switches, are you somehow inducing non-random / non-independent censoring, especially in the context of external controls where cross-over is more limited in trials and switches are more common in RWD?

Yes, generally treatment switches are often informative (which does not mean censoring is informative, see [Andersen [-@andersen_05]](papers/Andersen (2005, encyclopedia) Censored data.pdf)) as people are switching because their current treatment is not working. However, you could also imagine some scenarios where the reason for switching may not carry information about a patient, e.g. a region may limit the availability of a certain treatment to a limited number of cycles for cost-effectiveness reasons.


# Publicly available comments on molecules

## Polarix ODAC

Whether to censor at NALT or not was a question in the [Polarix ODAC](https://www.fda.gov/advisory-committees/advisory-committee-calendar/march-9-2023-meeting-oncologic-drugs-advisory-committee-meeting-announcement-03092023).

FDA's comments are available in Appendix 2 (p. 95ff) of [Genentech's briefing package](https://www.fda.gov/media/165961/download). Here, we summarize our view on some of FDA's comments.

### What is the primary question of interest?

FDA's proposed analysis of censoring at NALT, implying a hypothetical strategy for the ICE of NALT, insinuates interest in a treatment effect in a world where NALT would not exist. However, if Polivy is approved NALT will be available for patients.

### Relation between treatment policy and hypothetical strategy for an ICE of NALT

FDA comments:

> When comparing the treatment policy approach and the hypothetical approach, there are advantages and caveats to both. 

First and foremost, they answer **different** clinical questions. In our opinion which question is of most interest should guide the discussion.

### Consistency between estimates for two different estimands

FDA commented that 

> Therefore, neither approach is perfect and both strategies are important to characterize the effect of treatment. Ideally, they should be consistent and come to the same conclusion to demonstrate a robust PFS benefit.

Different handling of NALT corresponds to different estimands and we do not see a need that the answer to different scientific questions must necessarily be consistent.

### Further trials where Roche received similar feedback

- Polivy: [Polarix](https://www.clinicaltrials.gov/study/NCT03274492?distance=50&titles=polarix&rank=1), [Polargo](https://www.clinicaltrials.gov/study/NCT04182204?rank=1&limit=10&titles=polargo).
- Mosunetuzumab: [Sunmo](https://www.clinicaltrials.gov/study/NCT05171647?rank=1&limit=10&titles=Sunmo), [Celestimo](https://www.clinicaltrials.gov/study/NCT04712097?rank=1&limit=10&titles=Celestimo).
- Glofitamab: [Starglo](https://clinicaltrials.gov/study/NCT04408638), [Skyglo](https://www.clinicaltrials.gov/study/NCT06047080?titles=NCT06047080&rank=1).

## Sotorasib ODAC

[Briefing document](https://www.fda.gov/media/172696/download).

## Qing Xu's presentation at ASA Biopharmaceutical Section Regulatory-Industry Statistics Workshop

[Slidedeck](https://oncoestimand.github.io/oncowg_webpage/docs/talks/20230929/1_Xu.pdf).

### Non-random censoring

We would argue that foremost, a discussion of the estimand is needed before discussing estimation methods.

### Different estimands to quantify the effect: 

Summary comment:

> Different methods with different Estimand strategies should be conducted to ensure robustness. No single Estimand that fits all needs.

We agree to the general concept that multiple estimands will help quantify the treatment effect. However, that raises the question about whether and how to pick the primary estimand and how to decide about "success" of the trial.

# FDA / Lungevity statistical forum 12th October: Impact of Cross-over in the Evaluation of Overall Survival in Randomized Cancer Clinical Trials

Speakers:

- Prof. Nicholas R Latimer, University of Sheffield, UK
- Prof. Cheng Zheng, University of Nebraska, US
- Dr. Kaspar Rufibach, Roche Pharma, Switzerland

Slides of Kaspar Rufibach's presentation are available [here](https://numbersman77.github.io/kasparrufibach/files/talks/20231012_Rufibach_Lungevity_crossover.pdf).

Many of the above topics were raised in Kaspar's presentation, sharing Roche's experience in FDA interactions on Glofitamab. An additional point was that FDA suggested a hypothetical strategy for NALT for PFS, but discouraged a similar hypothetical strategy for crossover for OS. 

# Patient participation

We mention here [Rubin et al. [-@rubin_17]](papers/Rubin et al (2017) Strategies to Maximize Patient Participation in Clinical Trials.pdf).

# Appendix 

# Why is censoring of subjects in the estimator for a time-to-event endpoint implementing a hypothetical strategy?

Assume you have a trial with 100 patients and primary endpoint PFS. (In a frequentist world) This trial is a sample drawn from a metaphysical population, where the latter is our primary interest and one of the attributes of the estimand defintion. In the population PFS has a true survival function $S$.

In a first scenario, assume you observe PFS for all the 100 patients. Then, an unbiased estimator $\hat S_1$, such as e.g. Kaplan-Meier (which in this case is nothing else than 1 - CDF), estimates $S$.

Now assume a second scenario where 20 patients are **randomly censored** (following the terminology in Unkel et al. [-@unkel_19], based on @aalen_08). If we now estimate $S$ using an unbiased estimator $\hat S_2$, e.g. Kaplan-Meier, again then we are "correctly" using the information of the 20 censored patients, i.e. for these 20 patients "...outcome after $x$ number of months is imputed by using the longer term outcomes of other patients in their treatment group who also are free of the outcome at $x$ number of months and remain under follow-up beyond $x$ number of months." (terminology used in [Fleming et al. [-@fleming_09]](papers/Fleming et al (2009) Issues in Using PFS When Evaluating Oncology Products.pdf)). So indeed, the estimand we are targeting (namely the function $S$) remains the same as in the hypothetical world where censoring would not happen.

It is important to note that censoring alone is only sufficient for implementing a hypothetical strategy if censoring is, e.g., **random** in the sense described in, e.g., Unkel et al. [-@unkel_19]. This is essentially equivalent to the "missing-at-random" assumption for longitudinal outcomes.


# References

