---
title: "Publications of the group"
date: "Last change: `r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
bibliography: biblio.bib
---

Here we list the publications that the group has written or contributed to.

# Accepted or published

* Lawrence, R., Degtyarev, E., Griffiths, P., Trask, P., Lau, H., D'Alessio, D., Griebsch, I., Wallenstein, G., Cocks, K., Rufibach, K. _What is an estimand & how does it relate to quantifying the effect of treatment on patient-reported quality of life outcomes in clinical trials_ (2020). Journal of Patient-Reported Outcomes, **4(1)**, 68. [doi](https://jpro.springeropen.com/track/pdf/10.1186/s41687-020-00218-5). 
* Degtyarev, E., Rufibach, K., Shentu, Y., Yung, G., Casey, M., Englert, S., Liu, F., Liu, Y., Sailer, O., Siegel, J., Sun, S., Tang, R., Zhou, J. _Assessing the impact of COVID-19 on the objective and analysis of oncology clinical trials – application of the estimand framework_ (2020). Statistics in Biopharmaceutical Research, **12(4)**, 427-437. [doi](https://doi.org/10.1080/19466315.2020.1785543) | [arxiv](http://arxiv.org/abs/2006.04480).
* Casey M., Degtyarev E., Lechuga M.J., Aimone P., Ravaud A., Motzer R., Liu F., Stalbovskaya V., Tang R., Butler E., Sailer O., Halabi S., George D. _Estimand framework: Are we   asking the right question? A case study in the solid tumor setting_ (2020). Pharmaceutical Statistics, **20**, 324–334. [doi](https://doi.org/10.1002/pst.2079).
* Sun, S., Weber, J., Butler, E., Rufibach, K., Roychoudhury, S. _Estimands in Hematology Trials_ (2021). Pharmaceutical Statistics, 20, 793-805. [doi](https://doi.org/10.1002/pst.2108) | [arxiv](https://arxiv.org/abs/2010.00957). **This paper was the 3rd most downloaded paper that appeared in 2021 in [Pharmaceutical Statistics](https://onlinelibrary.wiley.com/journal/15391612).**
* Bornkamp, B., Rufibach, K., Lin, J., Liu, Y., Mehrotra, D., Roychoudhury, S., Schmidli, H., Shentu, Y., Wolbers, M. _Principal Stratum Strategy: Potential Role in Drug Development_ (2021). Pharmaceutical Statistics, **20**, 737-751. [doi](https://doi.org/10.1002/pst.2104) | [arxiv](https://arxiv.org/abs/2008.05406) | [github](https://github.com/oncoestimand/princ_strat_drug_dev) | [markdown](https://oncoestimand.github.io/princ_strat_drug_dev/princ_strat_example.html) | **This paper was the 4th most downloaded paper that appeared in 2021 in [Pharmaceutical Statistics](https://onlinelibrary.wiley.com/journal/15391612).**
* Manitz, J., Kan-Dobrosky, N., Buchner, H., Casadebaig, M.L., Degtyarev, E., Dey, J., Haddad, V., Fei, J., Martin, E., Mo, M., Rufibach, K., Shentu, Y., Stalbovskaya, V., Tang, R., Yung, G., Zhu, J. _Estimands for Overall Survival in Clinical Trials with Treatment Switching in Oncology_ (2022). Pharmaceutical Statistics, **21**, 150-162. [doi](https://doi.org/10.1002/pst.2158).
* Hampson, L.V., Degtyarev, E., Tang, R., Lin, J., Rufibach, K., Zheng, C. _Comment on [Biostatistical considerations when using RWD and RWE in clinical studies for regulatory purposes: A landscape assessment](https://doi.org/10.1080/19466315.2021.1883473)_ (2021). Statistics in Biopharmaceutical Research, to appear. [doi](https://doi.org/10.1080/19466315.2021.1994459).

# Submitted

* Siegel, J.M., Grinsted, L., Liu, F., Weber, J., Englert, S., Casey, M. _Censoring and censoring mechanisms in oncology in light of the estimands framework_ (2022). Submitted. | [arxiv](https://arxiv.org/abs/2203.01781).
* Siegel, J.M. Weber, J., Englert, S. _The Role of Occlusion: Potential Extension of the ICH E9 (R1) Addendum on Estimands and Sensitivity Analysis for Time-to-Event Oncology Studies_ (2022). Submitted. | [arxiv](https://arxiv.org/abs/2203.02182).
* Rufibach, K., Grinsted, L., Li, J., Weber, H.J., Zheng, C., and Zhou, J. _Quantification of Follow-up Time in Oncology Clinical Trials with a Time-to-Event Endpoint: Asking the Right Questions._ (2022). Submitted. | [arXiv](https://doi.org/10.48550/arxiv.2206.05216) | [github](https://github.com/oncoestimand/quantFU) | [markdown](https://oncoestimand.github.io/quantFU/quantFU.html).
* Liu, Y., Yang, M., Kil, S., Li, J., Mondal, S., Shentu, Y., Tian, H., Wang, L., Yung, G. _From logic-respecting efficacy estimands to logic-ensuring analysis principle for time-to-event endpoint in randomized clinical trials with subgroups._ (2022). Submitted. 
* Englert, S., Mercier, F., Pilling, E. A., Homer, V., Habermehl, C., Kan-Dobrosky, N. _Defining estimands for efficacy assessment in single arm Phase 1b or Phase 2 clinical trials in oncology early development._ (2022). Submitted.
* Mercier, F., Homer, V., Geng, J., Zhang, H., Englert, S., Kan-Dobrosky, N. _Estimands in oncology early clinical development: Assessing the impact of intercurrent events on the dose-toxicity relationship._ (2022). Submitted.



