---
title: "Publications of the group"
date: last-modified
execute:   
  freeze: auto  # re-render only when source changes
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: yes
    toc_depth: 3
    toc_float: yes
bibliography: biblio.bib
---

Here we list the publications that the group has written or contributed to.

# Accepted or published

1) Lawrance, R., Degtyarev, E., Griffiths, P., Trask, P., Lau, H., D'Alessio, D., Griebsch, I., Wallenstein, G., Cocks, K., Rufibach, K. _What is an estimand & how does it relate to quantifying the effect of treatment on patient-reported quality of life outcomes in clinical trials_ (2020). Journal of Patient-Reported Outcomes, **4(1)**, 68. | [doi](https://jpro.springeropen.com/track/pdf/10.1186/s41687-020-00218-5) | 
2) Degtyarev, E., Rufibach, K., Shentu, Y., Yung, G., Casey, M., Englert, S., Liu, F., Liu, Y., Sailer, O., Siegel, J., Sun, S., Tang, R., Zhou, J. _Assessing the impact of COVID-19 on the objective and analysis of oncology clinical trials – application of the estimand framework_ (2020). Statistics in Biopharmaceutical Research, **12(4)**, 427-437. | [doi](https://doi.org/10.1080/19466315.2020.1785543) | [arxiv](http://arxiv.org/abs/2006.04480) |
3) Casey M., Degtyarev E., Lechuga M.J., Aimone P., Ravaud A., Motzer R., Liu F., Stalbovskaya V., Tang R., Butler E., Sailer O., Halabi S., George D. _Estimand framework: Are we   asking the right question? A case study in the solid tumor setting_ (2020). Pharmaceutical Statistics, **20**, 324–334. | [doi](https://doi.org/10.1002/pst.2079) |
4) Sun, S., Weber, J., Butler, E., Rufibach, K., Roychoudhury, S. _Estimands in Hematology Trials_ (2021). Pharmaceutical Statistics, 20, 793-805. | [doi](https://doi.org/10.1002/pst.2108) | [arxiv](https://arxiv.org/abs/2010.00957) | **This paper was the 3rd most downloaded paper that appeared in 2021 in [Pharmaceutical Statistics](https://onlinelibrary.wiley.com/journal/15391612).**
5) Bornkamp, B., Rufibach, K., Lin, J., Liu, Y., Mehrotra, D., Roychoudhury, S., Schmidli, H., Shentu, Y., Wolbers, M. _Principal Stratum Strategy: Potential Role in Drug Development_ (2021). Pharmaceutical Statistics, **20**, 737-751. | [doi](https://doi.org/10.1002/pst.2104) | [arxiv](https://arxiv.org/abs/2008.05406) | [github](https://github.com/oncoestimand/princ_strat_drug_dev) | [markdown](https://oncoestimand.github.io/princ_strat_drug_dev/princ_strat_example.html) | **This paper was the 4th most downloaded paper that appeared in 2021 in [Pharmaceutical Statistics](https://onlinelibrary.wiley.com/journal/15391612).** | [Effective statistician podcast](https://theeffectivestatistician.com/a-deep-dive-into-principal-stratification-and-causal-inference/) |
6) Manitz, J., Kan-Dobrosky, N., Buchner, H., Casadebaig, M.L., Degtyarev, E., Dey, J., Haddad, V., Fei, J., Martin, E., Mo, M., Rufibach, K., Shentu, Y., Stalbovskaya, V., Tang, R., Yung, G., Zhu, J. _Estimands for Overall Survival in Clinical Trials with Treatment Switching in Oncology_ (2022). Pharmaceutical Statistics, **21**, 150-162. | [doi](https://doi.org/10.1002/pst.2158) | **This paper was among the most downloaded papers in the first twelve months following publication among those papers that appeared in 2021 in [Pharmaceutical Statistics](https://onlinelibrary.wiley.com/journal/15391612).**
7) Hampson, L.V., Degtyarev, E., Tang, R., Lin, J., Rufibach, K., Zheng, C. _Comment on [Biostatistical considerations when using RWD and RWE in clinical studies for regulatory purposes: A landscape assessment](https://doi.org/10.1080/19466315.2021.1883473)_ (2023). Statistics in Biopharmaceutical Research, **15(1)**, 23--26. | [doi](https://doi.org/10.1080/19466315.2021.1994459) |
8) Sridhara, R, Barksdale, E., Marchenko, O., Jiang, Q., Ando, Y., Bloomquist, E., Coory, M., Crouse, M., Degtyarev, E., Framke, T., Freidlin, B., Gerber, D.E., Gwise, T., Josephson, F., Hess, L., Kluetz, P., Li, D., Mandrekar, S., Posch, M., Rantell, K., Ratitch, B., Raven, A., Roes, K., Rufibach, K., Sarac, S.B., Simon, R., Singh, H., Theoret, M., Thomson, A., Zuber, E., Shen, Y.L., Pazdur, R. _Cancer Clinical Trials Beyond Pandemic: Report of an American Statistical Association Biopharmaceutical Section Open Forum Discussion_ (2023). Statistics in Biopharmaceutical Research, **15(2)**, 444--449. | [doi](https://doi.org/10.1080/19466315.2022.2103181) |
9) Rufibach, K., Grinsted, L., Li, J., Weber, H.J., Zheng, C., and Zhou, J. _Quantification of Follow-up Time in Oncology Clinical Trials with a Time-to-Event Endpoint: Asking the Right Questions._ (2023). Pharmaceutical Statistics, **22(4)**, 671-691. | [doi](https://doi.org/10.1002/pst.2300) | [arXiv](https://doi.org/10.48550/arxiv.2206.05216) | [github](https://github.com/oncoestimand/quantFU) | [markdown](https://oncoestimand.github.io/quantFU/quantFU.html) |
10) Liu, Y., Yang, M., Kil, S., Li, J., Mondal, S., Shentu, Y., Tian, H., Wang, L., Yung, G. _From logic-respecting efficacy estimands to logic-ensuring analysis principle for time-to-event endpoint in randomized clinical trials with subgroups._ (2023). Statistics in Biopharmaceutical Research, **15(3)**, 560--573. | [doi](https://doi.org/10.1080/19466315.2023.2186945) |
11) Englert, S., Mercier, F., Pilling, E. A., Homer, V., Habermehl, C., Kan-Dobrosky, N. _Defining estimands for efficacy assessment in single arm Phase 1b or Phase 2 clinical trials in oncology early development._ (2023+). Pharmaceutical Statistics, **22(5)**, 921-937. | [doi](https://doi.org/10.1002/pst.2319) |
12) Weber, H. J., Corson, S., Li, J., Mercier, F., Roychoudhury, S., Sailer, M. O., Sun, S., Todd, A., Yung, G. _Duration of and time to response in oncology clinical trials from the perspective of the estimand framework._ (2023+). Pharmaceutical Statistics, to appear. | [arXiv](https://arxiv.org/abs/2212.10911) | [doi](https://doi.org/10.1002/pst.2340) | [github](https://github.com/oncoestimand/dor) | [markdown](https://oncoestimand.github.io/dor/dor.html) |
13) Lawrance, R., Skaltsa, K., Regnault, A., Floden, L. _Reflections on estimands for patient-reported outcomes in cancer clinical trials._ (2023+). Journal of Biopharmaceutical Statistics, to appear. | [doi](https://doi.org/10.1080/10543406.2023.2280628) |
14) Mercier, F., Homer, V., Geng, J., Zhang, H., Englert, S., Kan-Dobrosky, N. _Estimands in oncology early clinical development: Assessing the impact of intercurrent events on the dose-toxicity relationship._ (2023+). Statistics in Biopharmaceutical Research, to appear. | [doi](https://doi.org/10.1080/19466315.2023.2296648) |
15) Wei, J., Xu, J., Bornkamp, B., Lin, R., Tian, H., Xi, D., Zhang, X., Zhao, Z., Roychoudhury, S. _Conditional and Unconditional treatment effects in randomized clinical trials: Estimands, Estimation, and Interpretation._ (2023+). Statistics in Biopharmaceutical Research, to appear. | [doi](https://doi.org/10.1080/19466315.2023.2292774) |
16) Siegel, J.M., Weber, H.J., Englert, S., Liu, F., Casey, M. _Time-to-event estimands and loss to follow-up in oncology in light of the estimands framework_ (2024+). Pharmaceutical Statistics, to appear. | [arxiv](https://arxiv.org/abs/2203.01781) | [doi](https://doi.org/10.1002/pst.2386) |.

# Submitted

<!-- * Siegel, J.M. Weber, J., Englert, S. _The Role of Occlusion: Potential Extension of the ICH E9 (R1) Addendum on Estimands and Sensitivity Analysis for Time-to-Event Oncology Studies_ (2022). Submitted. | [arxiv](https://arxiv.org/abs/2203.02182) |. -->
* Mozumder, S.I., Grinsted, L., Siegel, J.M., Liu, F., Weber, H., Englert, S. _Censoring Assumptions for Time-to-event Endpoints for Oncology Trials in Light of the Estimands Framework._ (2024+). Under revision.
