---
title: "Scope"
date: last-modified
execute:   
  freeze: auto  # re-render only when source changes
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
---

The estimand framework aims at aligning trial objectives and statistical analyses by demanding a precise definition of the inferential quantity of interest, the estimand. The addendum is anticipated to have a major impact on drug development, as the choice of an estimand will drive the trial design and sample size, conduct, data collection, and analysis of clinical trials moving forward. Furthermore, the framework is anticipated to facilitate discussions about relevant treatment effects, interpretation of study results, and added value of the drugs between sponsors, regulators, payers, physicians, and patients.

The need to amend E9 with a discussion on estimands grew out of the realization of an apparent lack of alignment between the objectives stated in a clinical trial protocol and the accompanying quantification and interpretation of the treatment effect reported in a regulatory submission. While the estimand framework has been developed with different clinical trial settings and endpoints in mind, the examples discussed in publications, at scientific meetings, and in the addendum have largely focused on symptomatic studies and continuous, longitudinal endpoints. However, in oncology primary endpoints in clinical trials are typically of the time-to-event (T2E) type (such as overall, progression-free, or event-free survival). For these endpoints, there are still many open questions concerning endpoint definition, data collection, analysis methodology, interpretation, and use in drug development. The working group aims at bringing together statisticians from industry, regulators, and academia to ensure common understanding and consistent definitions for key estimands in oncology across and share experiences, intercurrent events, and the used sensitivity analyses. Key questions that are discussed are:

-   How can time-to-event (T2E) endpoints be embedded in the addendum framework?
-   What are key estimands and intercurrent events in Oncology?
-   How do the five strategies to handle intercurrent events proposed in the ICH E9 addendum apply to T2E endpoints?
-   How can established methods to answer questions in oncology, e.g. treatment switching or various censoring schemes, be embedded in the addendum framework, what estimands has been usually targeted?
-   The addendum in its current version does not require a causal interpretation of a proposed estimand. However, are there parts in the drug development lifecycle that require a causal interpretation of an estimand?
-   Being aware that the hazard ratio from Cox regression does not admit a causal interpretation, what are effect measures for T2E endpoints that are amenable to a causal interpretation?
-   The addendum in its current version does not require a causal interpretation of a proposed estimand. However, are there parts in the drug development lifecycle that require a causal interpretation of an estimand?
-   Being aware that the hazard ratio from Cox regression does not admit a causal interpretation, what are effect measures for T2E endpoints that are amenable to such a causal interpretation?

Furthermore, increased transparency on the treatment effect of interest is considered an important goal of the addendum in order to facilitate discussions between different stakeholders. However, no guidance on protocol implementation has been provided so far, and there is a risk that the same estimand will be described in different ways by sponsors, potentially leading to confusion for regulators, physicians, patients, and possibly even inconsistent labels. Therefore, it is desired to ensure common understanding and consistent definitions for estimands across industry.
