---
title: "Oncology estimand working group: newsletter 11 October 2022"
date: "Last change: `r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: no
    toc_depth: 3
    toc_float: yes
---

```{r setup, include = FALSE, echo = FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)
```

Hi all,

We hope this reaches you well! It has been a while since we last reached out to the entire group. We would like to share some recent developments, events, and achievements.

- On June 28th & 29th we had two full group TCs with regulators attending where we presented our work. Slidedecks are available [here](https://oncoestimand.github.io/oncowg_webpage/docs/ha.html).
- Since the last newsletter one additional paper has been submitted ([Rufibach et al., 2022](https://arxiv.org/abs/2206.05216)). See the [publications page](https://oncoestimand.github.io/oncowg_webpage/docs/publications.html) for details. With submission of this paper (and the work on the revision) the _follow-up quantification task force_ has concluded its work.
- PSI has reached out to us: they are currently planning the 2023 PSI conference, to be held at the Novotel London West, Hammersmith from 12 to 14 June 2023. We are invited to run a session of our WG, details (speakers, abstracts, chair) of a suggested session are due **18th November**. Please get back to us in due time if you'd like to contribute to such a session, likely with results of task force work.
- We have updated the [events page](https://oncoestimand.github.io/oncowg_webpage/docs/events.html) with our past and upcoming appearances, including posting of presented slidedecks. **Please let us know of further presentations, workshops, webinars, etc that are not on the list yet!** - Please also share slidedecks or links to other material that we can add to the [events page](https://oncoestimand.github.io/oncowg_webpage/docs/events.html).
- [eunethta](https://www.eunethta.eu/) is currently seeking comments for their set of guidelines for a joint clinical assessment of European HTA bodies. Several of the WG's papers were cited in [EFPIA's response to deliverable 4.5](https://www.eunethta.eu/d4-5/).
- The [EFSPI/EFPIA Estimands Implementation WG (EIWG)](https://www.efspi.org/EFSPI/Working_Groups/EFSPI_EFPIA_EIWG.aspx) has published yet another paper [Principles and recommendations for incorporating estimands into clinical study protocol templates](https://trialsjournal.biomedcentral.com/articles/10.1186/s13063-022-06515-2). The paper is well worth a read.

To conclude, we invite you to regularly check out our webpage: [www.oncoestimand.org](http://www.oncoestimand.org).

Kind Regards,<br>
Evgeny & Kaspar