---
title: "Oncology estimand working group: newsletter 17th September 2021"
date: "Last change: `r format(Sys.time(), '%d %B, %Y')`"
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: no
    toc_depth: 3
    toc_float: yes
---

```{r setup, include = FALSE, echo = FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)
```

Hi all,

We hope this reaches you well! It has been a while since we last reached out to the entire group. We would like to share some recent developments, events, and achievements.

- Our [clinical engagement task force](https://oncoestimand.github.io/oncowg_webpage/docs/taskforces.html#1_Clinical_engagement) organized a second webinar targeting all our partner functions in pharma development. Find details on our [events page](https://oncoestimand.github.io/oncowg_webpage/docs/events.html) - registration is still open!
- We also contribute to several sessions at the upcoming ASA Biopharmaceutical Section Regulatory-Industry Statistics Workshop 2021, see again on the [events page](https://oncoestimand.github.io/oncowg_webpage/docs/events.html).
- Meanwhile, six papers out of our WG have been accepted or published. All of these are available for download in our gFolder [here](https://drive.google.com/drive/folders/1hpp-IFiFNLEN6GOA-p2ZWk4Rvmz-ZB3W?usp=sharing).
- 8 out of 9 [task forces](https://oncoestimand.github.io/oncowg_webpage/docs/taskforces.html) have started their work. We would also like to initiate work on task force 2 **Principal stratification for treatment switching** - if you’d be interested to contribute please let us know. We intend to kick this task force now, after the acceptance of the paper about treatment switching (see gFolder [here](https://drive.google.com/drive/folders/1hpp-IFiFNLEN6GOA-p2ZWk4Rvmz-ZB3W?usp=sharing)).
- We will also reach out to all task force leads to check in where their groups currently are and where the entire group can potentially support them. Our vision for 2022 is that we organize a _oncology estimand working group webinar series_ where task forces report on their work.
- Last week a 1 1/2 page [paper](https://jamanetwork.com/journals/jama/article-abstract/2783611) introducing estimands using the PIONEER trials as an example appeared in JAMA. Having more and more such papers likely opens the door for publishing on estimand topics in clinical journals and interacting more with clinicians. Of note that personally (KR) I do not agree how they define ITT - they mix up estimand attributes and analysis sets.
- Further past events of note where the [EFSPI regulatory statistics workshop](https://www.efspi.org/EFSPI/Events/Regulatory_Meetings/6th_efspi_workshop_on_regulatory_statistics.aspx) with a [talk](https://www.efspi.org/Documents/Events/Regulatory%20Meetings/2021/EFSPI%202021%20Day%202/21%20O'Kelly.pdf) by Michael O'Kelly on how to deal with multiple estimands per tial. Recordings will also be up soon! Several of our members were also involved in the discussion in the last FDA - lungevity meeting on NPH.
- Finally - are there any new estimand topics where this group could potentially contribute its knowledge and network? If you have such topics please do not hesitate to get back to us!

To conclude, we invite you to regularly check out our webpage: [www.oncoestimand.org](http://www.oncoestimand.org).

Kind Regards,<br>
Evgeny & Kaspar
