```{r echo = FALSE}
# how to do this with child documents: https://gist.github.com/rmoff/a043676a2f084b81a434

i <- as.numeric('{{i}}')
tab <- talks[i, ]
```

## `r paste(as.character(tab$date), " -- ", select(tab, Conference), sep = "")` {.tabset .tabset-fade .tabset-pills .unnumbered}

```{r, echo = FALSE, results = 'asis', message = FALSE, eval = TRUE}
panderOptions('knitr.auto.asis', FALSE)
t0 <- (tab %>% select(date, City, Country, Type))
#t0[, "Link to program"] <- paste("[Link to Program](", (tab %>% select(Web)), ")", sep = "")
rownames(t0) <- NULL
t0[is.na(t0)] <- ""
pander(t0)
```

### Program {.unnumbered}

`r ifelse(is.na(tab %>% select(Web)), "no program available", paste("[Link to Program](", tab %>% select(Web), ")", sep = ""))`

### Talks and/or recording {.unnumbered}

```{r echo = FALSE}
tab <- select(tab, -date)
tab2 <- data.frame(matrix(NA, ncol = 1, nrow = 5))
colnames(tab2) <- c("Speaker and Title")
ns <- as.numeric(substr(tail(colnames(tab), 1), 5, 5))
for (i in 1:ns){
  z1 <- tab[, paste("Speaker", i, sep = "")]
  if (is.na(tab[, paste("Talk", i, sep = "")])){
    z2 <- paste(tab[, paste("Title", i, sep = "")], sep = "")} else {
      z2 <- paste("[", tab[, paste("Title", i, sep = "")], "](", tab[, paste("Talk", i, sep = "")], ")", sep = "")
    }
  tab2[i, 1] <- paste(z1, ": ", z2, sep = "")
}

# nonempty rows
r <- sum((tab2 == "NA: [NA](NA)" | tab2 == "NA: NA") == FALSE, na.rm = TRUE)  
tab3 <- as.data.frame(tab2[1:r, ])
colnames(tab3) <- "Speaker (available slidedecks are linked)"
```

```{r, echo = FALSE, results = 'asis', message = FALSE, eval = TRUE}
kable(tab3)
```
