---
title: "Oncology estimand working group: newsletter 16th December 2022"
format:
  html:
    toc: true
    toc-depth: 2
    toc-title: Contents
    toc-location: left
    number-sections: true
    number-depth: 2
---

```{r setup, include = FALSE, echo = FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)
```

Hi all,

We hope this reaches you well! Before the end of the year we would like to share again some recent developments, events, and achievements.

# Updates

- We have updated the [events page](https://oncoestimand.github.io/oncowg_webpage/docs/events_past.html) with our past and upcoming appearances, including posting of presented slidedecks. **Please let us know of further presentations, workshops, webinars, etc that are not on the list yet!**
- On 21st October DIA held a webinar in China, with a talk by Jiajun Xu from the [conditional and marginal effect force](https://oncoestimand.github.io/oncowg_webpage/docs/taskforces.html#conditional-vs.-marginal-effects). With a peak attendance of 4460 this likely sets a new record for a talk by this WG!
- 2nd December: Together with ASA NJ chapter the WG co-organized a webinar [ASA New Jersey Chapter Webinar Series: Getting the question right: Applying the Estimand and Target Trial Frameworks with External Controls
](https://oncoestimand.github.io/oncowg_webpage/docs/events_past.html#asa-new-jersey-chapter-webinar-series-getting-the-question-right-applying-the-estimand-and-target-trial-frameworks-with-external-controls). See also [Evgeny's linkedin post](https://www.linkedin.com/posts/evgeny-degtyarev-b149507b_drugdevelopment-epidemiology-estimand-activity-7004960385795506176-D9Vy?utm_source=share&utm_medium=member_desktop).
- In December, the [Basel Biometrics Society](https://baselbiometrics.github.io/home/docs/) organized two half-day seminars on **Addressing intercurrent events: Treatment policy and hypothetical strategies** Slides and recordings are available [day 1](https://baselbiometrics.github.io/home/docs/events_past.html#joint-efspi-bbs-virtual-event---addressing-intercurrent-events-treatment-policy-and-hypothetical-strategies-day-1) and [day 2](https://baselbiometrics.github.io/home/docs/events_past.html#joint-efspi-bbs-virtual-event---addressing-intercurrent-events-treatment-policy-and-hypothetical-strategies-day-2).

# Plans for 2023

- Continue the work in the task forces.
- We are also again planning check-in TCs with our global regulatory partners and will reach out to task forces in due time.
- At least two conference appearances are already planned:
  - Talk at the [Duke Industry statistics symposium](https://oncoestimand.github.io/oncowg_webpage/docs/events_upcoming.html#duke-industry-statistics-symposium-2023).
  - Entire invited session at the [PSI conference](https://oncoestimand.github.io/oncowg_webpage/docs/events_upcoming.html#psi-conference).

# Action items for WG members
- Please routinely share slidedecks or links to other material that we can add to the [events page](https://oncoestimand.github.io/oncowg_webpage/docs/events_past.html).
 
You are invited to share the link to this newsletter broadly. To conclude, we invite you to regularly check out our webpage: [www.oncoestimand.org](http://www.oncoestimand.org).

Kind Regards,<br>
Evgeny & Kaspar
