---
title: "Oncology estimand working group: newsletter 17th July 2023"
format:
  html:
    toc: true
    toc-depth: 2
    toc-title: Contents
    toc-location: left
    number-sections: true
    number-depth: 2
bibliography: ../biblio.bib
---

```{r setup, include = FALSE, echo = FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)
```

Hi all,

We hope this reaches you well! Before we all leave for summer vacation we would like to share again some recent developments, events, and achievements.

# Updates

- Since the last newsletter the following publications have been **accepted** or already **appeared**:
  - @rufibach_23fu, including [code](https://oncoestimand.github.io/quantFU/quantFU.html).
  - @liu_23logic .
  - @englert_23 .

- We have updated the [events page](https://oncoestimand.github.io/oncowg_webpage/docs/events_past.html) with our past and upcoming appearances, including posting of presented slidedecks. **Please let us know of further presentations, workshops, webinars, etc that are not on the list yet!**
- Conferences: the working group contributed
  - a session to the [PSI 2023 conference](https://oncoestimand.github.io/oncowg_webpage/docs/events_past.html#psi-conference) in London. Hong Tian, Konstantina Skaltsa, Stefan Englert, Lynda Grinsted, Elizabeth Pilling, and Yufei Wang presented outcomes from various taskforces to a completely full room.
  - even organized two sessions at the [LIDS 2023 conference](https://oncoestimand.github.io/oncowg_webpage/docs/events_past.html#lifetime-data-science-conference-lids) in Raleigh.
  - co-organized and contributed to a BBS seminar on [Quantification of risk: ask the right questions or time to apply the estimand framework to safety!](https://baselbiometrics.github.io/home/docs/events_past.html#quantification-of-risk-ask-the-right-questions-or-time-to-apply-the-estimand-framework-to-safety).
  - Jonathan gave an invited talk at the [Duke industry statistics symposium 2023](https://oncoestimand.github.io/oncowg_webpage/docs/events_past.html#duke-industry-statistics-symposium-2023).
  
# Upcoming events and potential meet-up

## JSM in Toronto

If there is interest we are happy to organize a get together, e.g. dinner. Please reach out to [Kaspar Rufibach](mailto:kaspar.rufibach@roche.com) in case you are interested and provide the nights you'd be available.

## ISCB in Milan

Kaspar will participate, feel free to reach out (I will only be there Mon - Wed and very busy, but happy to catch up during coffee break).

## CEN in Basel

If there is interest we are happy to organize a get together, e.g. dinner. Please reach out to [Kaspar Rufibach](mailto:kaspar.rufibach@roche.com) in case you are interested and provide the nights you'd be available.

## EFSPI regulatory statistics workshop

If there is interest we are happy to organize a get together, e.g. dinner. Please reach out to [Kaspar Rufibach](mailto:kaspar.rufibach@roche.com) in case you are interested and provide the nights you'd be available.
 
## ASA FDA workshop

I invite our US colleagues to also organize a get together there.

# Action items for WG members

- Please routinely share slidedecks or links to other material that we can add to the [events page](https://oncoestimand.github.io/oncowg_webpage/docs/events_past.html).
 
You are invited to share the link to this newsletter broadly. To conclude, we invite you to regularly check out our webpage: [www.oncoestimand.org](http://www.oncoestimand.org).

Kind Regards,<br>
Evgeny & Kaspar

# References



