---
title: "Oncology estimand working group: newsletter 11 October 2022"
output: 
  rmarkdown::html_document:
    highlight: pygments
    number_sections: yes
    self_contained: yes
    toc: no
    toc_depth: 3
    toc_float: yes
---

```{r setup, include = FALSE, echo = FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)
```

Hi all,

We hope this reaches you well! It has been a while since we last reached out to the entire group. We would like to share some recent developments, events, and achievements.

# Updates

- Since the last newsletter three additional paper have been submitted ([Rufibach et al., 2022](https://arxiv.org/abs/2206.05216), Englert et al., 2022, Mercier et al., 2022). See the [publications page](https://oncoestimand.github.io/oncowg_webpage/docs/publications.html) for details. With submission of this paper (and the work on the revision) the [follow-up quantification task force](https://oncoestimand.github.io/oncowg_webpage/docs/taskforces.html#21_Quantification_of_follow-up) has concluded its work.
- We have updated the [events page](events_past.html) with our past and upcoming appearances, including posting of presented slidedecks. **Please let us know of further presentations, workshops, webinars, etc that are not on the list yet!**
- On 21st October DIA held a webinar in China, with a talk by Jiajun Xu from the [conditional and marginal effect force](taskforces.html#conditional-vs.-marginal-effects). With a peak attendance of 4460 this likely sets a new record for a talk by this WG!
- 15th November: Together with ASA NJ chapter the WG is co-organizing a webinar [ASA New Jersey Chapter Webinar Series: Getting the question right: Applying the Estimand and Target Trial Frameworks with External Controls
](communication/20221202_ASA_NJ_TTF_estimands.pdf).

# Action items for WG members
- Please also share slidedecks or links to other material that we can add to the [events page](https://oncoestimand.github.io/oncowg_webpage/docs/events_past.html).
 
You are invited to share the link to this newsletter broadly. To conclude, we invite you to regularly check out our webpage: [www.oncoestimand.org](http://www.oncoestimand.org).

Kind Regards,<br>
Evgeny & Kaspar
