---
title: "Oncology estimand working group: newsletter 23 May 2022"
format:
  html:
    toc: true
    toc-depth: 2
    toc-title: Contents
    toc-location: left
    number-sections: true
    number-depth: 2
---

```{r setup, include = FALSE, echo = FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)
```

Hi all,

We hope this reaches you well! It has been a while since we last reached out to the entire group. We would like to share some recent developments, events, and achievements.

- Since the last newsletter one additional paper has been accepted ([Hampson et al., 2022](https://doi.org/10.1080/19466315.2021.1883473)) and two papers have been submitted ([Siegel et al., 2022a](https://arxiv.org/abs/2203.01781) and [Siegel et al., 2022b](https://arxiv.org/abs/2203.02182)), summarizing the work of the censoring subteam. See the [publications page](publications.html) for details.
- We have updated the [events page](events_past.html) with our past and upcoming appearances. Here are some of the upcoming highlights where the WG will contribute:
  - Two WG talks at the [Society for Clinical Trials](https://www.sctweb.org/meeting/) conference.
  - [ASA biopharm section webinar](https://www.eventbrite.com/e/logic-respecting-efficacy-estimands-to-logic-ensuring-analysis-principle-tickets-336986344227).
  - The WG has organized an entire session at the [PSI conference](https://psiweb.org/conferences/about-the-conference) and Stefan Englert will present a poster.
  - WG talks at the [International Chinese Statistical Association Applied Statistics Symposium](https://symposium2022.icsa.org/), [JSM](https://ww2.amstat.org/meetings/jsm/2022/), [ISCB](https://www.iscb.info/iscb-annual-conference/), [ISOQoL](https://www.isoqol.org/events/29th-annual-conference/).
  - Contributed topic session at the [ASA FDA workshop](https://ww2.amstat.org/meetings/biop/2022/).

  Find details on WG speakers, dates, and session / talk titles on our [events page](../events_past.html). **Please let us know of further presentations, workshops, webinars, etc that are not on the list yet!** And send us slidedecks to be posted on the webpage.

- Please also share slidedecks or links to other material that we can add to the [events page](../events_past.html).
- The [engagement task force](../taskforces.html#estimands-engagement) has put together a nice poster that will be presented at conferences in [Europe](../talks/20220612_OncoEstimand-Poster-PSI-Final.pdf), [Asia](../talks/20220721_OncoEstimand-Poster-China-Final.pdf), and the [US](../talks/20220920_OncoEstimand-Poster-BIOP-Final.pdf). This may serve as a good resource if you'd like to present the WG.
- The 7th [EFSPI regulatory statistics workshop](https://efspi.org/Documents/Events/Events%202021/7th%20Reg.pdf) will again take place face-to-face in Basel this year. Check out the draft program, it is already very exciting! Stefan will again present the WG poster there in a session featuring several EFSPI / PSI special interest groups.
- EMA has issued [Advice to sponsors on managing the impact of the war in Ukraine on clinical trials](https://www.ema.europa.eu/en/news/advice-sponsors-managing-impact-war-ukraine-clinical-trials) which heavily uses the estimand framework. They call out the hypothetical estimand strategy specifically. 
- The [EFSPI/EFPIA Estimands Implementation WG (EIWG)](https://www.efspi.org/EFSPI/Working_Groups/EFSPI_EFPIA_EIWG.aspx) has published a paper [Marking 2-Years of New Thinking in Clinical Trials: The Estimand Journey](https://link.springer.com/article/10.1007/s43441-022-00402-3). The paper is well worth a read.
- On June 28th & 29th we will again have full group TCs with regulators attending (you should have invites in your calendars). We plan to run these sessions as the last ones, i.e. each task force is asked to present the status of their work.

To conclude, we invite you to regularly check out our webpage: [www.oncoestimand.org](http://www.oncoestimand.org).

Kind Regards,<br>
Evgeny & Kaspar
