---
title: "Oncology estimand working group: newsletter 11 October 2022"
format:
  html:
    toc: true
    toc-depth: 2
    toc-title: Contents
    toc-location: left
    number-sections: true
    number-depth: 2
---

```{r setup, include = FALSE, echo = FALSE}
## load packages
packs.html <- c("knitr", "pander", "reporttools", "dplyr", "readxl")
for (i in 1:length(packs.html)){library(packs.html[i], character.only = TRUE)}

knitr::opts_chunk$set(echo = TRUE)
```

Hi all,

We hope this reaches you well! It has been a while since we last reached out to the entire group. We would like to share some recent developments, events, and achievements.

# Updates

- On June 28th & 29th we had two full group TCs with regulators attending where we presented our work. Slidedecks are available [here](../ha.html).
- Since the last newsletter three additional paper have been submitted ([Rufibach et al., 2022](https://arxiv.org/abs/2206.05216), Englert et al., 2022, Mercier et al., 2022). See the [publications page](../publications.html) for details. With submission of this paper (and the work on the revision) the [follow-up quantification task force](../taskforces.html#quantification-of-follow-up) has concluded its work.
- We have updated the [events page](../events_past.html) with our past and upcoming appearances, including posting of presented slidedecks. **Please let us know of further presentations, workshops, webinars, etc that are not on the list yet!**
- The WG has organized two sessions at the [ASA FDA workshop](https://ww2.amstat.org/meetings/biop/2022/) ("Adjusted and Unadjusted Estimate in Clinical Trials: Reward, Risk and Myth" and "Estimands in Oncology: A Topical Panel Discussion"), see [events page](../events_past.html#20092022:_ASA_Biopharmaceutical_Section_Regulatory-Industry_Statistics_Workshop), 
- Two webinars are currently being planned:
  - 21st October: DIA webinar in China on conditional vs. marginal treatment effect. Jiajun Xu from the [conditional and marginal effect task force](../taskforces.html#conditional-vs.-marginal-effects) will present, and panelists from FDA, academia and industry will discuss.
  - 2nd December: estimands for RWE, featuring speakers from FDA, EMA, NICE, academia and industry. Agenda and registration details available [here](20221202_ASA_NJ_TTF_estimands.pdf).
- [eunethta](https://www.eunethta.eu/) is currently seeking comments for their set of guidelines for a joint clinical assessment of European HTA bodies. Several of the WG's papers were cited in [EFPIA's response to deliverable 4.5](https://www.eunethta.eu/d4-5/).
- The [EFSPI/EFPIA Estimands Implementation WG (EIWG)](https://www.efspi.org/EFSPI/Working_Groups/EFSPI_EFPIA_EIWG.aspx) has published yet another paper [Principles and recommendations for incorporating estimands into clinical study protocol templates](https://trialsjournal.biomedcentral.com/articles/10.1186/s13063-022-06515-2). The paper is well worth a read.

# Action items for WG members
- PSI has reached out to us: they are currently planning the 2023 PSI conference, to be held at the Novotel London West, Hammersmith from 12 to 14 June 2023. We are invited to run a session of our WG, details (speakers, abstracts, chair) of a suggested session are due **18th November**. Please get back to us in due time if you'd like to contribute to such a session, likely with results of task force work.
- Please also share slidedecks or links to other material that we can add to the [events page](../events_past.html).
 
You are invited to share the link to this newsletter broadly. To conclude, we invite you to regularly check out our webpage: [www.oncoestimand.org](http://www.oncoestimand.org).

Kind Regards,<br>
Evgeny & Kaspar
